package com.hieuwu.supabasestorageclient.observability.crashlytics

import kotlin.experimental.ExperimentalNativeApi
import kotlinx.cinterop.ExperimentalForeignApi
import platform.Foundation.NSNumber
import platform.Foundation.numberWithBool
import platform.Foundation.numberWithDouble
import platform.Foundation.numberWithFloat
import platform.Foundation.numberWithInt
import platform.Foundation.numberWithLongLong

// Symbols come from the `firebaseKmp` cinterop generated by the spmForKmp plugin
// (see composeApp/build.gradle.kts -> swiftPackageConfig); each exported SPM product gets its
// own Kotlin package named after the product.
import FirebaseCore.FIRApp
import FirebaseCrashlytics.FIRCrashlytics
import FirebaseCrashlytics.FIRExceptionModel
import FirebaseCrashlytics.FIRStackFrame

@OptIn(ExperimentalForeignApi::class)
actual object AppCrashlytics {

    private val crashlytics: FIRCrashlytics
        get() = FIRCrashlytics.crashlytics()

    /**
     * Configures the default `FIRApp` if the host app has not done so already.
     * Requires `GoogleService-Info.plist` to be bundled with the iOS app target.
     */
    actual fun initialize() {
        if (FIRApp.defaultApp() == null) {
            FIRApp.configure()
        }
    }

    actual fun log(message: String) {
        crashlytics.log(message)
    }

    @OptIn(ExperimentalNativeApi::class)
    actual fun recordException(throwable: Throwable) {
        val model = FIRExceptionModel.exceptionModelWithName(
            name = throwable::class.qualifiedName ?: "KotlinException",
            reason = buildReason(throwable),
        )
        model.stackTrace = throwable.getStackTrace().map { symbol ->
            FIRStackFrame.stackFrameWithSymbol(symbol = symbol, file = "", line = 0)
        }
        crashlytics.recordExceptionModel(model)
    }

    actual fun setUserId(userId: String?) {
        crashlytics.setUserID(userId ?: "")
    }

    actual fun setCustomKey(key: String, value: String) {
        crashlytics.setCustomValue(value, forKey = key)
    }

    actual fun setCustomKey(key: String, value: Boolean) {
        crashlytics.setCustomValue(NSNumber.numberWithBool(value), forKey = key)
    }

    actual fun setCustomKey(key: String, value: Int) {
        crashlytics.setCustomValue(NSNumber.numberWithInt(value), forKey = key)
    }

    actual fun setCustomKey(key: String, value: Long) {
        crashlytics.setCustomValue(NSNumber.numberWithLongLong(value), forKey = key)
    }

    actual fun setCustomKey(key: String, value: Float) {
        crashlytics.setCustomValue(NSNumber.numberWithFloat(value), forKey = key)
    }

    actual fun setCustomKey(key: String, value: Double) {
        crashlytics.setCustomValue(NSNumber.numberWithDouble(value), forKey = key)
    }

    /** Crashlytics only shows one reason line, so the cause chain is flattened into it. */
    private fun buildReason(throwable: Throwable): String = buildString {
        append(throwable.message ?: throwable.toString())
        var cause = throwable.cause
        while (cause != null) {
            append(" <- ").append(cause::class.simpleName).append(": ").append(cause.message)
            cause = cause.cause
        }
    }
}
