package com.hieuwu.supabasestorageclient.observability.analytics

import kotlinx.cinterop.ExperimentalForeignApi
import platform.Foundation.NSNumber
import platform.Foundation.numberWithDouble
import platform.Foundation.numberWithLongLong

// Symbols come from the `firebaseKmp` cinterop generated by the spmForKmp plugin
// (see composeApp/build.gradle.kts -> swiftPackageConfig); each exported SPM product gets its
// own Kotlin package named after the product.
import FirebaseAnalytics.FIRAnalytics
import FirebaseCore.FIRApp

@OptIn(ExperimentalForeignApi::class)
actual object AppAnalytics {

    /**
     * Configures the default `FIRApp` if the host app has not done so already.
     * Requires `GoogleService-Info.plist` to be bundled with the iOS app target.
     */
    actual fun initialize() {
        if (FIRApp.defaultApp() == null) {
            FIRApp.configure()
        }
    }

    actual fun setEnabled(enabled: Boolean) {
        FIRAnalytics.setAnalyticsCollectionEnabled(enabled)
    }

    actual fun logEvent(name: String, params: Map<String, Any?>) {
        val normalized = normalizeAnalyticsParams(params)
        val parameters: Map<Any?, Any> = normalized.mapValues { (_, value) ->
            when (value) {
                is Long -> NSNumber.numberWithLongLong(value)
                is Double -> NSNumber.numberWithDouble(value)
                else -> value
            }
        }
        FIRAnalytics.logEventWithName(name, parameters.ifEmpty { null })
    }

    actual fun setUserId(userId: String?) {
        FIRAnalytics.setUserID(userId)
    }

    actual fun setUserProperty(name: String, value: String?) {
        FIRAnalytics.setUserPropertyString(value, forName = name)
    }
}
